# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1074, 852)
        MainWindow.setMinimumSize(QtCore.QSize(420, 660))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.controlGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlGroupBox.sizePolicy().hasHeightForWidth())
        self.controlGroupBox.setSizePolicy(sizePolicy)
        self.controlGroupBox.setMinimumSize(QtCore.QSize(300, 650))
        self.controlGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controlGroupBox.setFont(font)
        self.controlGroupBox.setStyleSheet(_fromUtf8("<html><head/><body><p><span style=\" color:#5500ff;\">Structural Colouration Demo</span></p></body></html>"))
        self.controlGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.controlGroupBox.setObjectName(_fromUtf8("controlGroupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.controlGroupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.cyl_view_widget = CylGLView(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cyl_view_widget.sizePolicy().hasHeightForWidth())
        self.cyl_view_widget.setSizePolicy(sizePolicy)
        self.cyl_view_widget.setMinimumSize(QtCore.QSize(200, 250))
        self.cyl_view_widget.setObjectName(_fromUtf8("cyl_view_widget"))
        self.verticalLayout_10.addWidget(self.cyl_view_widget)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.diameter_label = QtGui.QLabel(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameter_label.sizePolicy().hasHeightForWidth())
        self.diameter_label.setSizePolicy(sizePolicy)
        self.diameter_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.diameter_label.setFont(font)
        self.diameter_label.setObjectName(_fromUtf8("diameter_label"))
        self.verticalLayout_7.addWidget(self.diameter_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.diameter_slider = QtGui.QSlider(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameter_slider.sizePolicy().hasHeightForWidth())
        self.diameter_slider.setSizePolicy(sizePolicy)
        self.diameter_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.diameter_slider.setBaseSize(QtCore.QSize(0, 0))
        self.diameter_slider.setMinimum(300)
        self.diameter_slider.setMaximum(450)
        self.diameter_slider.setSingleStep(10)
        self.diameter_slider.setProperty("value", 400)
        self.diameter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.diameter_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.diameter_slider.setTickInterval(10)
        self.diameter_slider.setObjectName(_fromUtf8("diameter_slider"))
        self.horizontalLayout_2.addWidget(self.diameter_slider)
        self.diameter_value_label = QtGui.QLabel(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameter_value_label.sizePolicy().hasHeightForWidth())
        self.diameter_value_label.setSizePolicy(sizePolicy)
        self.diameter_value_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.diameter_value_label.setFont(font)
        self.diameter_value_label.setObjectName(_fromUtf8("diameter_value_label"))
        self.horizontalLayout_2.addWidget(self.diameter_value_label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.period_label = QtGui.QLabel(self.controlGroupBox)
        self.period_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.period_label.setFont(font)
        self.period_label.setObjectName(_fromUtf8("period_label"))
        self.verticalLayout_7.addWidget(self.period_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.period_slider = QtGui.QSlider(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period_slider.sizePolicy().hasHeightForWidth())
        self.period_slider.setSizePolicy(sizePolicy)
        self.period_slider.setMinimum(600)
        self.period_slider.setMaximum(1400)
        self.period_slider.setSingleStep(10)
        self.period_slider.setProperty("value", 1000)
        self.period_slider.setOrientation(QtCore.Qt.Horizontal)
        self.period_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.period_slider.setTickInterval(50)
        self.period_slider.setObjectName(_fromUtf8("period_slider"))
        self.horizontalLayout_3.addWidget(self.period_slider)
        self.period_value_label = QtGui.QLabel(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period_value_label.sizePolicy().hasHeightForWidth())
        self.period_value_label.setSizePolicy(sizePolicy)
        self.period_value_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.period_value_label.setFont(font)
        self.period_value_label.setObjectName(_fromUtf8("period_value_label"))
        self.horizontalLayout_3.addWidget(self.period_value_label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.colour_label = QtGui.QLabel(self.controlGroupBox)
        self.colour_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.colour_label.setFont(font)
        self.colour_label.setObjectName(_fromUtf8("colour_label"))
        self.verticalLayout_7.addWidget(self.colour_label)
        self.colour_box = QtGui.QLabel(self.controlGroupBox)
        self.colour_box.setMinimumSize(QtCore.QSize(0, 30))
        self.colour_box.setMaximumSize(QtCore.QSize(16777215, 30))
        self.colour_box.setAutoFillBackground(True)
        self.colour_box.setFrameShape(QtGui.QFrame.Box)
        self.colour_box.setLineWidth(1)
        self.colour_box.setText(_fromUtf8(""))
        self.colour_box.setObjectName(_fromUtf8("colour_box"))
        self.verticalLayout_7.addWidget(self.colour_box)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.refl_graph = CurveWidget(self.controlGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refl_graph.sizePolicy().hasHeightForWidth())
        self.refl_graph.setSizePolicy(sizePolicy)
        self.refl_graph.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.refl_graph.setFont(font)
        self.refl_graph.setOrientation(QtCore.Qt.Horizontal)
        self.refl_graph.setObjectName(_fromUtf8("refl_graph"))
        self.verticalLayout_10.addWidget(self.refl_graph)
        self.horizontalLayout.addWidget(self.controlGroupBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.graphicsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.graphicsGroupBox.setMinimumSize(QtCore.QSize(700, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.graphicsGroupBox.setFont(font)
        self.graphicsGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsGroupBox.setFlat(False)
        self.graphicsGroupBox.setObjectName(_fromUtf8("graphicsGroupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.graphicsGroupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.graphics_view_widget = SVGPaintView(self.graphicsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view_widget.sizePolicy().hasHeightForWidth())
        self.graphics_view_widget.setSizePolicy(sizePolicy)
        self.graphics_view_widget.setMinimumSize(QtCore.QSize(299, 300))
        self.graphics_view_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphics_view_widget.setObjectName(_fromUtf8("graphics_view_widget"))
        self.verticalLayout_8.addWidget(self.graphics_view_widget)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.nano_view_widget = CylGLView(self.graphicsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nano_view_widget.sizePolicy().hasHeightForWidth())
        self.nano_view_widget.setSizePolicy(sizePolicy)
        self.nano_view_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.nano_view_widget.setObjectName(_fromUtf8("nano_view_widget"))
        self.horizontalLayout_6.addWidget(self.nano_view_widget)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.reset_button = QtGui.QPushButton(self.graphicsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setMinimumSize(QtCore.QSize(50, 0))
        self.reset_button.setObjectName(_fromUtf8("reset_button"))
        self.verticalLayout_8.addWidget(self.reset_button)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.horizontalLayout.addWidget(self.graphicsGroupBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#5500ff;\">Structural Colouration Demo</span></p></body></html>", None))
        self.controlGroupBox.setTitle(_translate("MainWindow", "Create a Colour", None))
        self.diameter_label.setText(_translate("MainWindow", "Diameter", None))
        self.diameter_value_label.setText(_translate("MainWindow", "100 (nm)", None))
        self.period_label.setText(_translate("MainWindow", "Period", None))
        self.period_value_label.setText(_translate("MainWindow", "500 (nm)", None))
        self.colour_label.setText(_translate("MainWindow", "Colour", None))
        self.graphicsGroupBox.setTitle(_translate("MainWindow", "Visualisation", None))
        self.reset_button.setText(_translate("MainWindow", "Reset", None))

from CylGLView import CylGLView
from SVGPaintView import SVGPaintView
from guiqwt.plot import CurveWidget
